package bus

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/decred/dcrd/dcrec/secp256k1/v4"
)

// vectorFile mirrors testdata/v1/bus/bus_envelope_v2_vectors.json, which is
// generated by two implementations independent of this package (noble/TypeScript
// for digests and signatures, a standalone Python script re-deriving preimages
// and digests). This test is the third leg of the cross-check.
//
// The file lives in the repository fixture tree rather than under this package
// so that it is covered by testdata/v1/manifest.json and published as a release
// asset: other languages consume the same bytes this test asserts against.
type vectorFile struct {
	Domain              string          `json:"domain"`
	PayloadDomain       string          `json:"payload_domain"`
	PrivateKey          string          `json:"private_key"`
	PublicKeyCompressed string          `json:"public_key_compressed"`
	Cases               []vectorCase    `json:"cases"`
	BuilderEvidence     builderEvidence `json:"builder_evidence"`
}

// builderEvidence mirrors the linked Builder evidence vectors in the fixture.
// The Go constants in evidence_test.go and this fixture are two copies of one
// contract, so TestBuilderEvidenceFixtureMatchesConstants compares them: the
// fixture is what other languages consume, and a fixture that drifted from the
// Go tests would let this repository pass while its published vectors were wrong.
type builderEvidence struct {
	ContentDomain    string `json:"content_domain"`
	EvidenceIDDomain string `json:"evidence_id_domain"`
	FaultIDDomain    string `json:"fault_id_domain"`
	Envelopes        []struct {
		Name             string `json:"name"`
		PayloadHex       string `json:"payload_hex"`
		PayloadDigest    string `json:"payload_digest"`
		BusSigningDigest string `json:"bus_signing_digest"`
		Signature        string `json:"signature"`
		EnvelopeBytes    string `json:"envelope_bytes"`
	} `json:"envelopes"`
	LinkedCases []struct {
		Name                    string `json:"name"`
		OneofTag                uint32 `json:"oneof_tag"`
		EvidenceKind            int32  `json:"evidence_kind"`
		EvidenceBytes           string `json:"evidence_bytes"`
		Violation               int32  `json:"violation"`
		ContentPreimage         string `json:"content_preimage"`
		CanonicalEvidenceDigest string `json:"canonical_evidence_digest"`
		EvidenceIDPreimage      string `json:"evidence_id_preimage"`
		EvidenceID              string `json:"evidence_id"`
		FaultIDPreimage         string `json:"fault_id_preimage"`
		FaultID                 string `json:"fault_id"`
	} `json:"linked_cases"`
	StructuralCases []struct {
		Name            string `json:"name"`
		OneofTag        uint32 `json:"oneof_tag"`
		EvidenceBytes   string `json:"evidence_bytes"`
		TaskID          string `json:"task_id"`
		VerifyRound     uint32 `json:"verify_round"`
		BuilderOperator string `json:"builder_operator"`
	} `json:"structural_cases"`
	MalformedOuterCases []struct {
		Name          string `json:"name"`
		EvidenceBytes string `json:"evidence_bytes"`
		ErrorCategory string `json:"error_category"`
		ErrorContains string `json:"error_contains"`
	} `json:"malformed_outer_cases"`
}

type vectorCase struct {
	Name   string `json:"name"`
	Fields struct {
		SchemaVersion             uint32 `json:"schema_version"`
		ChainID                   string `json:"chain_id"`
		Subject                   string `json:"subject"`
		Kind                      int32  `json:"kind"`
		SenderParticipantType     int32  `json:"sender_participant_type"`
		SenderOperatorAddress     string `json:"sender_operator_address"`
		ServiceAuthorizationNonce string `json:"service_authorization_nonce"`
		MessageID                 string `json:"message_id"`
		Nonce                     string `json:"nonce"`
		IssuedAtUnixMS            string `json:"issued_at_unix_ms"`
		ExpiresAtUnixMS           string `json:"expires_at_unix_ms"`
		PayloadType               int32  `json:"payload_type"`
	} `json:"fields"`
	SenderOperatorCodecBytes string `json:"sender_operator_codec_bytes"`
	PayloadHex               string `json:"payload_hex"`
	Expected                 struct {
		PayloadDigest   string `json:"payload_digest"`
		SigningPreimage string `json:"signing_preimage"`
		SigningDigest   string `json:"signing_digest"`
		Signature       string `json:"signature"`
	} `json:"expected"`
}

func mustHex(t *testing.T, value string) []byte {
	t.Helper()
	raw, err := hex.DecodeString(value)
	if err != nil {
		t.Fatalf("bad hex in vector: %v", err)
	}
	return raw
}

func mustU64(t *testing.T, value string) uint64 {
	t.Helper()
	var out uint64
	for i := 0; i < len(value); i++ {
		out = out*10 + uint64(value[i]-'0')
	}
	return out
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "testdata", "v1", "bus", "bus_envelope_v2_vectors.json"))
	if err != nil {
		t.Fatal(err)
	}
	var file vectorFile
	if err := json.Unmarshal(raw, &file); err != nil {
		t.Fatal(err)
	}
	if file.Domain != Domain {
		t.Fatalf("vector domain %q != implementation domain %q", file.Domain, Domain)
	}
	if file.PayloadDomain != PayloadDomain {
		t.Fatalf("vector payload domain %q != implementation payload domain %q", file.PayloadDomain, PayloadDomain)
	}
	return file
}

func TestPayloadPreimageMinimumVector(t *testing.T) {
	want := "545255454f50454e5f4652414d455f563100000017545255454f50454e5f4255535f5041594c4f41445f56320000000000000001ff"
	if got := hex.EncodeToString(PayloadPreimage([]byte{0xff})); got != want {
		t.Fatalf("payload preimage mismatch\n got %s\nwant %s", got, want)
	}
}

func vectorFields(t *testing.T, c vectorCase) Fields {
	t.Helper()
	return Fields{
		SchemaVersion:             c.Fields.SchemaVersion,
		ChainID:                   c.Fields.ChainID,
		Subject:                   c.Fields.Subject,
		Kind:                      c.Fields.Kind,
		SenderParticipantType:     c.Fields.SenderParticipantType,
		SenderOperatorAddress:     c.Fields.SenderOperatorAddress,
		ServiceAuthorizationNonce: mustU64(t, c.Fields.ServiceAuthorizationNonce),
		MessageID:                 c.Fields.MessageID,
		Nonce:                     mustHex(t, c.Fields.Nonce),
		IssuedAtUnixMS:            mustU64(t, c.Fields.IssuedAtUnixMS),
		ExpiresAtUnixMS:           mustU64(t, c.Fields.ExpiresAtUnixMS),
		PayloadType:               c.Fields.PayloadType,
		PayloadDigest:             mustHex(t, c.Expected.PayloadDigest),
	}
}

func TestVectorsCrossCheck(t *testing.T) {
	file := loadVectors(t)
	privKey := secp256k1.PrivKeyFromBytes(mustHex(t, file.PrivateKey))
	pubKey := privKey.PubKey().SerializeCompressed()
	if hex.EncodeToString(pubKey) != file.PublicKeyCompressed {
		t.Fatalf("public key mismatch: %x", pubKey)
	}
	for _, c := range file.Cases {
		t.Run(c.Name, func(t *testing.T) {
			fields := vectorFields(t, c)

			payloadDigest := PayloadDigest(mustHex(t, c.PayloadHex))
			if hex.EncodeToString(payloadDigest[:]) != c.Expected.PayloadDigest {
				t.Fatalf("payload digest mismatch: %x", payloadDigest)
			}
			codec, err := OperatorAddressCodecBytes(fields.SenderOperatorAddress)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(codec) != c.SenderOperatorCodecBytes {
				t.Fatalf("operator codec bytes mismatch: %x", codec)
			}
			preimage, err := SigningPreimage(fields)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(preimage) != c.Expected.SigningPreimage {
				t.Fatalf("preimage mismatch\n got %x", preimage)
			}
			digest, err := SigningDigest(fields)
			if err != nil {
				t.Fatal(err)
			}
			if hex.EncodeToString(digest[:]) != c.Expected.SigningDigest {
				t.Fatalf("signing digest mismatch: %x", digest)
			}
			// dcrec RFC6979 must reproduce noble's deterministic signature
			signature := SignDigest(privKey, digest)
			if hex.EncodeToString(signature) != c.Expected.Signature {
				t.Fatalf("signature mismatch\n got %x\nwant %s", signature, c.Expected.Signature)
			}
			if err := VerifyDigestSignature(pubKey, digest[:], signature); err != nil {
				t.Fatalf("verify: %v", err)
			}
		})
	}
}

// TestVectorsFieldMutations flips every projection field and asserts the
// digest moves, so no field can be silently dropped from the preimage.
func TestVectorsFieldMutations(t *testing.T) {
	file := loadVectors(t)
	base := vectorFields(t, file.Cases[0])
	baseDigest, err := SigningDigest(base)
	if err != nil {
		t.Fatal(err)
	}
	mutations := map[string]func(Fields) Fields{
		"chain_id":                func(f Fields) Fields { f.ChainID += "x"; return f },
		"subject":                 func(f Fields) Fields { f.Subject += "x"; return f },
		"kind+payload_type":       func(f Fields) Fields { f.Kind = KindVerifyResult; f.PayloadType = PayloadTypeVerifyResultV1; return f },
		"sender_participant_type": func(f Fields) Fields { f.SenderParticipantType = ParticipantBuilder; return f },
		"sender_operator_address": func(f Fields) Fields {
			f.SenderOperatorAddress = "trueopen1870sqtdru7dj3xgwpzcexry0dwvyz2ku7xv9mg"
			return f
		},
		"service_authorization_nonce": func(f Fields) Fields { f.ServiceAuthorizationNonce++; return f },
		"message_id":                  func(f Fields) Fields { f.MessageID += "x"; return f },
		"nonce":                       func(f Fields) Fields { n := bytes.Clone(f.Nonce); n[0] ^= 1; f.Nonce = n; return f },
		"issued_at_unix_ms":           func(f Fields) Fields { f.IssuedAtUnixMS++; return f },
		"expires_at_unix_ms":          func(f Fields) Fields { f.ExpiresAtUnixMS++; return f },
		"payload_digest":              func(f Fields) Fields { d := bytes.Clone(f.PayloadDigest); d[31] ^= 1; f.PayloadDigest = d; return f },
	}
	for name, mutate := range mutations {
		t.Run(name, func(t *testing.T) {
			digest, err := SigningDigest(mutate(base))
			if err != nil {
				t.Fatal(err)
			}
			if digest == baseDigest {
				t.Fatalf("mutating %s did not change the signing digest", name)
			}
		})
	}
}

// TestBuilderEvidenceFixtureMatchesConstants closes the gap between the
// published fixture and this package's own vectors. keeper_api_contract.md §5.5
// requires the wire fixtures to contain both linked vectors byte for byte, so
// the fixture is authoritative for other languages; this asserts the Go tests
// assert the same bytes, and that the implementation reproduces them.
func TestBuilderEvidenceFixtureMatchesConstants(t *testing.T) {
	file := loadVectors(t)
	evidence := file.BuilderEvidence

	if evidence.ContentDomain != EvidenceContentDomain ||
		evidence.EvidenceIDDomain != EvidenceIDDomain ||
		evidence.FaultIDDomain != BuilderFaultDomain {
		t.Fatalf("fixture domains %+v do not match the implementation", evidence)
	}
	if len(evidence.Envelopes) != 2 || len(evidence.LinkedCases) != 2 ||
		len(evidence.StructuralCases) != 1 || len(evidence.MalformedOuterCases) != 8 {
		t.Fatalf("fixture has envelopes=%d linked=%d structural=%d malformed=%d, want 2/2/1/8",
			len(evidence.Envelopes), len(evidence.LinkedCases),
			len(evidence.StructuralCases), len(evidence.MalformedOuterCases))
	}

	wantEnvelopes := map[string]struct{ bytes, payloadDigest, signingDigest string }{
		"envelope_a": {envelopeABytes, envelopeAPayloadDigest, envelopeABusSigningDigest},
		"envelope_b": {envelopeBBytes, envelopeBPayloadDigest, envelopeBBusSigningDigest},
	}
	for _, got := range evidence.Envelopes {
		want, ok := wantEnvelopes[got.Name]
		if !ok {
			t.Fatalf("fixture has unexpected envelope %q", got.Name)
		}
		if got.EnvelopeBytes != want.bytes || got.PayloadDigest != want.payloadDigest ||
			got.BusSigningDigest != want.signingDigest {
			t.Fatalf("fixture %s does not match the Go vectors", got.Name)
		}

		// The fixture is not just compared, it is executed: every published
		// envelope has to decode and verify with the fixture's own key.
		verified, err := VerifyEvidenceEnvelope(mustHex(t, got.EnvelopeBytes), EvidenceVerifyOptions{
			ChainID:   evidenceChainID,
			LookupKey: testProofKey(t),
		})
		if err != nil {
			t.Fatalf("fixture %s failed the proof-only profile: %v", got.Name, err)
		}
		if hex.EncodeToString(verified.SigningDigest[:]) != want.signingDigest {
			t.Fatalf("fixture %s signing digest mismatch", got.Name)
		}
		if hex.EncodeToString(mustHex(t, got.PayloadHex)) != hex.EncodeToString(verified.Payload) {
			t.Fatalf("fixture %s payload_hex is not the payload inside envelope_bytes", got.Name)
		}
	}

	for _, linked := range evidence.LinkedCases {
		if _, err := EvidenceKindForTag(linked.OneofTag); err != nil {
			t.Fatalf("fixture case %q uses tag %d: %v", linked.Name, linked.OneofTag, err)
		}
		kind, err := EvidenceKindForTag(linked.OneofTag)
		if err != nil || kind != linked.EvidenceKind {
			t.Fatalf("fixture case %q maps tag %d to kind %d, implementation says %d",
				linked.Name, linked.OneofTag, linked.EvidenceKind, kind)
		}
		outer, err := DecodeBuilderEvidenceV2(mustHex(t, linked.EvidenceBytes))
		if err != nil {
			t.Fatalf("fixture case %q outer evidence failed strict decode: %v", linked.Name, err)
		}
		if outer.EvidenceTag != linked.OneofTag {
			t.Fatalf("fixture case %q outer tag %d, want %d", linked.Name, outer.EvidenceTag, linked.OneofTag)
		}

		var content [32]byte
		switch linked.OneofTag {
		case EvidenceTagEquivocation:
			if outer.Equivocation == nil ||
				hex.EncodeToString(outer.Equivocation.EnvelopeA) != envelopeABytes ||
				hex.EncodeToString(outer.Equivocation.EnvelopeB) != envelopeBBytes {
				t.Fatalf("fixture case %q outer equivocation fields do not retain the exact envelopes", linked.Name)
			}
			content, err = EquivocationDigest(EquivocationContent{
				DigestA: mustHex(t, envelopeABusSigningDigest),
				DigestB: mustHex(t, envelopeBBusSigningDigest),
			})
		case EvidenceTagInvalidStageSubmission:
			if outer.InvalidStageSubmission == nil ||
				hex.EncodeToString(outer.InvalidStageSubmission.Envelope) != envelopeABytes ||
				outer.InvalidStageSubmission.Violation != linked.Violation {
				t.Fatalf("fixture case %q outer invalid-stage fields mismatch", linked.Name)
			}
			content, err = InvalidStageDigest(InvalidStageContent{
				SigningDigest: mustHex(t, envelopeABusSigningDigest),
				Violation:     linked.Violation,
			})
		default:
			t.Fatalf("fixture case %q has no linked-vector coverage here", linked.Name)
		}
		if err != nil {
			t.Fatal(err)
		}
		if got := hex.EncodeToString(content[:]); got != linked.CanonicalEvidenceDigest {
			t.Fatalf("fixture case %q content digest %s, implementation produced %s",
				linked.Name, linked.CanonicalEvidenceDigest, got)
		}
		// The published preimage has to be the one that hashes to the published
		// digest, or a consumer re-deriving it byte by byte would diverge here.
		if got := sha256.Sum256(mustHex(t, linked.ContentPreimage)); hex.EncodeToString(got[:]) != linked.CanonicalEvidenceDigest {
			t.Fatalf("fixture case %q content_preimage does not hash to its declared digest", linked.Name)
		}

		evidenceID, err := EvidenceID(evidenceChainID, evidenceSenderAddress, kind, evidenceTaskID(), content)
		if err != nil {
			t.Fatal(err)
		}
		if got := hex.EncodeToString(evidenceID[:]); got != linked.EvidenceID {
			t.Fatalf("fixture case %q evidence_id %s, implementation produced %s", linked.Name, linked.EvidenceID, got)
		}
		faultID, err := FaultID(evidenceChainID, evidenceSenderAddress, kind, evidenceTaskID(), content)
		if err != nil {
			t.Fatal(err)
		}
		if got := hex.EncodeToString(faultID[:]); got != linked.FaultID {
			t.Fatalf("fixture case %q fault_id %s, implementation produced %s", linked.Name, linked.FaultID, got)
		}

		// The identity preimages get the same treatment as content_preimage
		// above. They are published as release assets precisely so another
		// language can re-derive an identity byte by byte instead of trusting
		// this implementation; an unasserted preimage is a published value that
		// nothing keeps honest, and it would be wrong in exactly the direction
		// that produces two chains disagreeing about one fault's identity.
		for _, identity := range []struct {
			label    string
			preimage string
			digest   string
		}{
			{"evidence_id", linked.EvidenceIDPreimage, linked.EvidenceID},
			{"fault_id", linked.FaultIDPreimage, linked.FaultID},
		} {
			if identity.preimage == "" {
				t.Fatalf("fixture case %q publishes no %s_preimage", linked.Name, identity.label)
			}
			if got := sha256.Sum256(mustHex(t, identity.preimage)); hex.EncodeToString(got[:]) != identity.digest {
				t.Fatalf("fixture case %q %s_preimage does not hash to its declared %s",
					linked.Name, identity.label, identity.label)
			}
		}
	}

	for _, structural := range evidence.StructuralCases {
		outer, err := DecodeBuilderEvidenceV2(mustHex(t, structural.EvidenceBytes))
		if err != nil {
			t.Fatalf("fixture structural case %q failed strict decode: %v", structural.Name, err)
		}
		if outer.EvidenceTag != structural.OneofTag || outer.DataUnavailable == nil {
			t.Fatalf("fixture structural case %q projected the wrong branch: %+v", structural.Name, outer)
		}
		if hex.EncodeToString(outer.DataUnavailable.TaskID) != structural.TaskID ||
			outer.DataUnavailable.VerifyRound != structural.VerifyRound ||
			outer.DataUnavailable.BuilderOperator != structural.BuilderOperator {
			t.Fatalf("fixture structural case %q fields mismatch: %+v", structural.Name, outer.DataUnavailable)
		}
	}

	for _, malformed := range evidence.MalformedOuterCases {
		_, err := DecodeBuilderEvidenceV2(mustHex(t, malformed.EvidenceBytes))
		if err == nil {
			t.Fatalf("fixture malformed case %q was accepted", malformed.Name)
		}
		if malformed.ErrorCategory != "STRICT_DECODE" || !errors.Is(err, ErrDecode) {
			t.Fatalf("fixture malformed case %q category=%q err=%v", malformed.Name, malformed.ErrorCategory, err)
		}
		if !strings.Contains(err.Error(), malformed.ErrorContains) {
			t.Fatalf("fixture malformed case %q rejected for the wrong reason: %v", malformed.Name, err)
		}
	}
}
